server:
  port: 8081

spring:
  application:
    name: gateway-server
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: http://localhost:8124/
          predicates:
            - Path=/user-service/**
        - id: student_route
          uri: http://localhost:8123/
          predicates:
            - Path=/student-service/**

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://center-server:8080/eureka
    register-with-eureka: true


logging:
  level:
    org:
      springframework:
        cloud:
          gateway: trace