server:
  port: 8124
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service

  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: postgres
    password: root

    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://center-server:8080/eureka
    register-with-eureka: false
