server:
  port: 8124
  servlet:
    context-path: /user-service

spring:
  application:
    name: user-service

  mvc:
    pathmatch:
      # 配置策略
      matching-strategy: ant-path-matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/study
    username: postgres
    password: root

    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000

  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
#    password:
    # 连接超时时间
    timeout: 20s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://center-server:8080/eureka
    register-with-eureka: false


# spring 监控
management:
  endpoints:
    web:
      exposure:
        include: "*"